#!/usr/bin/env python3
"""Render deterministic Markdown registers from an SEO teardown's canonical JSON."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any

GENERATED_NOTICE = "<!-- Generated by seo-teardown/scripts/render_handoff.py. Do not edit directly. -->"


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def text(value: Any) -> str:
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, (int, float)):
        return str(value)
    value = str(value).strip()
    return value or "None"


def inline_list(values: Any) -> str:
    if values is None:
        return "None"
    if not isinstance(values, list):
        return text(values)
    if not values:
        return "None"
    return ", ".join(text(item) for item in values)


def bullet_list(values: Any, indent: str = "") -> list[str]:
    if not isinstance(values, list) or not values:
        return [f"{indent}- None"]
    return [f"{indent}- {text(item)}" for item in values]


def md_cell(value: Any) -> str:
    return text(value).replace("|", "\\|").replace("\n", "<br>")


def render_implementation(findings_data: dict[str, Any]) -> str:
    findings = {item["id"]: item for item in findings_data.get("findings", [])}
    audit = findings_data.get("audit", {})
    lines = [
        GENERATED_NOTICE,
        "",
        "# Implementation sequence",
        "",
        f"**Review status:** {text(audit.get('review_status'))}",
        "",
        "The sequence is dependency-aware. Finding order is canonical in `findings.json`.",
        "",
    ]

    for phase in findings_data.get("implementation_phases", []):
        lines.extend(
            [
                f"## {text(phase.get('id'))} — {text(phase.get('title'))}",
                "",
                f"**Rationale:** {text(phase.get('rationale'))}",
                "",
                f"**Validation gate:** {text(phase.get('validation_gate'))}",
                "",
                f"**Expected outcome:** {text(phase.get('expected_outcome'))}",
                "",
                "| Finding | Order | Disposition | Severity | Status | Dependencies | Rationale |",
                "|---|---:|---|---|---|---|---|",
            ]
        )
        phase_findings = [findings[fid] for fid in phase.get("finding_ids", []) if fid in findings]
        phase_findings.sort(key=lambda item: item.get("implementation", {}).get("order", 0))
        for finding in phase_findings:
            implementation = finding.get("implementation", {})
            deps = finding.get("dependencies", [])
            lines.append(
                "| {id} | {order} | {disposition} | {severity} | {status} | {deps} | {rationale} |".format(
                    id=md_cell(finding.get("id")),
                    order=md_cell(implementation.get("order")),
                    disposition=md_cell(implementation.get("disposition")),
                    severity=md_cell(finding.get("severity")),
                    status=md_cell(finding.get("status")),
                    deps=md_cell(inline_list(deps)),
                    rationale=md_cell(implementation.get("rationale")),
                )
            )
        lines.append("")

    lines.extend(["## Complete finding ledger", "", "Every finding appears exactly once below.", ""])
    ordered = sorted(
        findings.values(), key=lambda item: item.get("implementation", {}).get("order", 0)
    )
    for finding in ordered:
        impl = finding.get("implementation", {})
        lines.append(
            f"- {finding.get('id')} — phase {impl.get('phase_id')}, order {impl.get('order')}, "
            f"disposition {impl.get('disposition')}"
        )
    lines.append("")
    return "\n".join(lines)


def render_serp_winners(item: dict[str, Any]) -> str:
    winner = item.get("winner_observation", {})
    status = winner.get("status")
    if status == "observed":
        parts = []
        for result in winner.get("results", []):
            value = text(result.get("value"))
            position = text(result.get("position"))
            parts.append(f"{value} ({position})")
        return inline_list(parts)
    return f"{text(status)} — {text(winner.get('reason'))}"


def render_method_evidence(item: dict[str, Any]) -> str:
    parts = []
    for method in item.get("method_evidence", []):
        parts.append(
            f"{text(method.get('method'))}={text(method.get('status'))}: "
            f"{text(method.get('observation'))} [evidence: {inline_list(method.get('evidence_ids'))}; "
            f"limits: {inline_list(method.get('limitations'))}]"
        )
    return inline_list(parts)


def render_url_observation(item: dict[str, Any], key: str) -> str:
    observation = item.get(key, {})
    status = text(observation.get("status"))
    value = observation.get("value")
    rendered_value = "None" if value is None else text(value)
    return (
        f"{status}: {rendered_value}; methods={inline_list(observation.get('supported_by_methods'))}; "
        f"evidence={inline_list(observation.get('evidence_ids'))}; "
        f"limits={inline_list(observation.get('limitations'))}"
    )


def render_coverage(coverage_data: dict[str, Any], findings_data: dict[str, Any]) -> str:
    findings = findings_data.get("findings", [])
    evidence = findings_data.get("evidence_sources", [])
    severity_counts = Counter(item.get("severity") for item in findings)
    status_counts = Counter(item.get("status") for item in findings)
    kind_counts = Counter(item.get("kind") for item in findings)

    lines = [
        GENERATED_NOTICE,
        "",
        "# Review coverage",
        "",
        f"**Review status:** {text(coverage_data.get('review_status'))}",
        "",
        "## Evidence and access ledger",
        "",
        "| Access category | Status | Coverage window | Material to comprehensive | Evidence | Limitations | Next step |",
        "|---|---|---|---|---|---|---|",
    ]
    for item in coverage_data.get("access", []):
        lines.append(
            "| {category} | {status} | {window} | {material} | {evidence} | {limits} | {next_step} |".format(
                category=md_cell(item.get("category")),
                status=md_cell(item.get("status")),
                window=md_cell(item.get("coverage_window")),
                material=md_cell(item.get("material_to_comprehensive")),
                evidence=md_cell(inline_list(item.get("evidence_ids"))),
                limits=md_cell(inline_list(item.get("limitations"))),
                next_step=md_cell(item.get("next_step")),
            )
        )

    lines.extend(
        [
            "",
            "## Audit module ledger",
            "",
            "| Module | Applicable | Materiality | Status | Findings | Evidence | Limitations | Next step |",
            "|---|---|---|---|---|---|---|---|",
        ]
    )
    for item in coverage_data.get("modules", []):
        lines.append(
            "| {module} | {applicable} | {materiality} | {status} | {checks} | {findings} | {evidence} | {limits} | {next_step} |".format(
                module=md_cell(item.get("id")),
                applicable=md_cell(item.get("applicable")),
                materiality=md_cell(item.get("materiality")),
                status=md_cell(item.get("status")),
                checks=md_cell(inline_list(item.get("check_ids"))),
                findings=md_cell(inline_list(item.get("finding_ids"))),
                evidence=md_cell(inline_list(item.get("evidence_ids"))),
                limits=md_cell(inline_list(item.get("limitations"))),
                next_step=md_cell(item.get("next_step")),
            )
        )

    lines.extend([
        "",
        "## Surface check ledger",
        "",
        "| Check | Module | Facet | Method | Status | Findings | Evidence | Available work completed | Result | Unknowns | Limitation refs | Limitations |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ])
    for item in coverage_data.get("surface_checks", []):
        lines.append(
            "| {id} | {module} | {facet} | {method} | {status} | {findings} | {evidence} | {completed} | {result} | {unknowns} | {refs} | {limits} |".format(
                id=md_cell(item.get("id")), module=md_cell(item.get("module_id")),
                facet=md_cell(item.get("facet")), method=md_cell(item.get("method")),
                status=md_cell(item.get("status")), findings=md_cell(inline_list(item.get("finding_ids"))),
                evidence=md_cell(inline_list(item.get("evidence_ids"))), completed=md_cell(item.get("available_work_completed")),
                result=md_cell(item.get("result")), unknowns=md_cell(inline_list(item.get("unknowns"))),
                refs=md_cell(inline_list(item.get("limitation_refs"))), limits=md_cell(inline_list(item.get("limitations"))),
            )
        )

    lines.extend([
        "",
        "## SERP sample ledger",
        "",
        "| Sample | Query | Surface | Location | Device | Observed | Features | Winners | Target | Evidence | Limitations |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ])
    for item in coverage_data.get("serp_samples", []):
        lines.append(
            "| {id} | {query} | {surface} | {location} | {device} | {date} | {features} | {winners} | {target} | {evidence} | {limits} |".format(
                id=md_cell(item.get("id")), query=md_cell(item.get("query")), surface=md_cell(item.get("engine_or_surface")),
                location=md_cell(item.get("location")), device=md_cell(item.get("device")), date=md_cell(item.get("observed_at")),
                features=md_cell(inline_list(item.get("result_features"))), winners=md_cell(render_serp_winners(item)),
                target=md_cell(item.get("target_observation")), evidence=md_cell(inline_list(item.get("evidence_ids"))),
                limits=md_cell(inline_list(item.get("limitations"))),
            )
        )

    lines.extend([
        "",
        "## URL sample ledger",
        "",
        "| Sample | URL | Role | Method evidence | Revision alignment | HTTP observation | Eligibility observation | Index observation | Canonical observation | Render observation | Findings | Evidence | Limitations |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ])
    for item in coverage_data.get("url_samples", []):
        lines.append(
            "| {id} | {url} | {role} | {methods} | {alignment} | {http} | {eligibility} | {index_state} | {canonical} | {render} | {findings} | {evidence} | {limits} |".format(
                id=md_cell(item.get("id")), url=md_cell(item.get("url")), role=md_cell(item.get("role")),
                methods=md_cell(render_method_evidence(item)), alignment=md_cell(item.get("source_revision_alignment")),
                http=md_cell(render_url_observation(item, "http_observation")),
                eligibility=md_cell(render_url_observation(item, "eligibility_observation")),
                index_state=md_cell(render_url_observation(item, "index_observation")),
                canonical=md_cell(render_url_observation(item, "canonical_observation")),
                render=md_cell(render_url_observation(item, "render_observation")), findings=md_cell(inline_list(item.get("finding_ids"))),
                evidence=md_cell(inline_list(item.get("evidence_ids"))), limits=md_cell(inline_list(item.get("limitations"))),
            )
        )

    lines.extend(["", "## Deliberate non-pursuits", ""])
    for item in coverage_data.get("deliberate_non_pursuits", []):
        lines.append(f"- **{text(item.get('topic'))}:** {text(item.get('rationale'))} (evidence: {inline_list(item.get('evidence_ids'))})")
    if not coverage_data.get("deliberate_non_pursuits"):
        lines.append("- None")

    lines.extend(["", "## Material limitations", ""])
    limitations = coverage_data.get("material_limitations", [])
    if limitations:
        for item in limitations:
            if isinstance(item, dict):
                lines.append(
                    f"- **{text(item.get('id'))}:** {text(item.get('description'))} "
                    f"(status: {text(item.get('status'))}; completion requirement: "
                    f"{text(item.get('completion_requirement'))})"
                )
            else:
                lines.append(f"- {text(item)}")
    else:
        lines.append("- None")

    lines.extend(["", "## Narrative reconciliation", ""])
    reconciliation = coverage_data.get("narrative_reconciliation", [])
    lines.extend(
        [
            "| Narrative location | Finding IDs | Non-actionable explanation |",
            "|---|---|---|",
        ]
    )
    for item in reconciliation:
        lines.append(
            "| {location} | {ids} | {explanation} |".format(
                location=md_cell(item.get("location")),
                ids=md_cell(inline_list(item.get("finding_ids"))),
                explanation=md_cell(item.get("non_actionable_explanation")),
            )
        )

    lines.extend(
        [
            "",
            "## Counts",
            "",
            f"- Evidence sources: {len(evidence)}",
            f"- Findings: {len(findings)}",
            f"- Severity: {', '.join(f'{key}={value}' for key, value in sorted(severity_counts.items())) or 'None'}",
            f"- Status: {', '.join(f'{key}={value}' for key, value in sorted(status_counts.items())) or 'None'}",
            f"- Kind: {', '.join(f'{key}={value}' for key, value in sorted(kind_counts.items())) or 'None'}",
            "",
            "## Validator",
            "",
        ]
    )
    validator = coverage_data.get("validator", {})
    lines.extend(
        [
            f"- **Command:** `{text(validator.get('command'))}`",
            f"- **Recorded result:** {text(validator.get('result'))}",
            "",
        ]
    )
    return "\n".join(lines)


def render_findings(findings_data: dict[str, Any]) -> str:
    evidence_map = {item.get("id"): item for item in findings_data.get("evidence_sources", [])}
    findings = sorted(findings_data.get("findings", []), key=lambda item: item.get("id", ""))
    lines = [
        GENERATED_NOTICE,
        "",
        "# Findings register",
        "",
        "`findings.json` is authoritative. This file is a deterministic rendering of the canonical objects.",
        "",
    ]

    for finding in findings:
        priority = finding.get("priority", {})
        measurement = finding.get("measurement", {})
        implementation = finding.get("implementation", {})
        search_state = finding.get("search_state", {})
        conversion = finding.get("conversion_linkage", {})
        scope = finding.get("implementation_scope", {})
        verification_context = finding.get("verification_context", {})
        lines.extend(
            [
                f"## {text(finding.get('id'))} — {text(finding.get('title'))}",
                "",
                f"- **Kind:** {text(finding.get('kind'))}",
                f"- **Domain:** {text(finding.get('domain'))}",
                f"- **Status:** {text(finding.get('status'))}",
                f"- **Severity:** {text(finding.get('severity'))}",
                f"- **Confidence:** {text(finding.get('confidence'))}",
                f"- **Evidence quality:** {text(finding.get('evidence_quality'))}",
                f"- **Claim basis:** {text(finding.get('claim_basis'))}",
                f"- **Likelihood:** {text(finding.get('likelihood'))}",
                f"- **Action:** {text(finding.get('action'))}",
                f"- **Platforms:** {inline_list(finding.get('platforms'))}",
                f"- **Affected queries:** {inline_list(finding.get('affected_queries'))}",
                f"- **Affected URLs or entities:** {inline_list(finding.get('affected_urls_or_entities'))}",
                f"- **Dependencies:** {inline_list(finding.get('dependencies'))}",
                f"- **Conflicts:** {inline_list(finding.get('conflicts'))}",
                f"- **Blocker:** {text(finding.get('blocker'))}",
                f"- **Owner decision:** {text(finding.get('owner_decision'))}",
                "",
                "### Evidence",
                "",
            ]
        )
        links = {item.get("evidence_id"): item for item in finding.get("evidence_links", []) if isinstance(item, dict)}
        for evidence_id in finding.get("evidence_ids", []):
            source = evidence_map.get(evidence_id, {})
            link = links.get(evidence_id, {})
            lines.append(
                f"- **{evidence_id} — {text(source.get('title'))}:** role={text(link.get('role'))}; "
                f"supported claim={text(link.get('claim'))}. Source summary: {text(source.get('summary'))} "
                f"(class: {text(source.get('evidence_class'))}; accessed: {text(source.get('accessed_at'))}; "
                f"limitations: {text(source.get('limitations'))})"
            )
        if not finding.get("evidence_ids"):
            lines.append("- None")

        lines.extend(
            [
                "",
                "### Project-specific consequence",
                "",
                f"**Business impact:** {text(finding.get('business_impact'))}",
                "",
                f"**Search consequence:** {text(finding.get('search_consequence'))}",
                "",
                f"**Reproduction:** {text(finding.get('reproduction'))}",
                "",
                f"**Root cause:** {text(finding.get('root_cause'))}",
                "",
                "### Search-state calibration",
                "",
                f"- **Technical eligibility:** {text(search_state.get('technical_eligibility'))}",
                f"- **Observed performance:** {text(search_state.get('observed_performance'))}",
                f"- **Consequence type:** {text(search_state.get('consequence_type'))}",
                "",
                "### Qualified-conversion linkage",
                "",
                f"- **Conversion target:** {text(conversion.get('conversion_target'))}",
                f"- **Funnel stage:** {text(conversion.get('funnel_stage'))}",
                f"- **Qualifiedness:** {text(conversion.get('qualifiedness'))}",
                f"- **Measurement status:** {text(conversion.get('measurement_status'))}",
                "",
                "### Recommendation and tradeoffs",
                "",
                f"**Recommendation:** {text(finding.get('recommendation'))}",
                "",
                f"**If implemented:** {text(finding.get('if_implemented'))}",
                "",
                f"**If unchanged:** {text(finding.get('if_unchanged'))}",
                "",
                "### Acceptance criteria",
                "",
            ]
        )
        lines.extend(bullet_list(finding.get("acceptance_criteria")))
        lines.extend(["", "### Verification", ""])
        lines.extend(bullet_list(finding.get("verification")))
        lines.extend(
            [
                "",
                "### Priority calibration",
                "",
                f"- **Expected business value:** {text(priority.get('expected_business_value'))}",
                f"- **Effort:** {text(priority.get('effort'))}",
                f"- **Reversibility:** {text(priority.get('reversibility'))}",
                f"- **Time to evidence:** {text(priority.get('time_to_evidence'))}",
                f"- **Downside:** {text(priority.get('downside'))}",
                "",
                "### Measurement",
                "",
                f"- **Baseline:** {text(measurement.get('baseline'))}",
                f"- **Primary metric:** {text(measurement.get('primary_metric'))}",
                f"- **Guardrail metrics:** {inline_list(measurement.get('guardrail_metrics'))}",
                f"- **Time horizon:** {text(measurement.get('time_horizon'))}",
                f"- **Confounders:** {inline_list(measurement.get('confounders'))}",
                f"- **Rollback criteria:** {text(measurement.get('rollback_criteria'))}",
                f"- **Decision rule:** {text(measurement.get('decision_rule'))}",
                "",
                "### Implementation handoff",
                "",
                f"- **Phase:** {text(implementation.get('phase_id'))}",
                f"- **Order:** {text(implementation.get('order'))}",
                f"- **Disposition:** {text(implementation.get('disposition'))}",
                f"- **Rationale:** {text(implementation.get('rationale'))}",
                f"- **Validation gate:** {text(implementation.get('validation_gate'))}",
                f"- **Targets:** {inline_list(scope.get('targets'))}",
                f"- **Non-goals:** {inline_list(scope.get('non_goals'))}",
                f"- **Owner or external actions:** {inline_list(scope.get('owner_or_external_actions'))}",
                f"- **Verification mode:** {text(verification_context.get('mode'))}",
                f"- **Verification environment:** {text(verification_context.get('environment'))}",
                f"- **Verification limitations:** {inline_list(verification_context.get('limitations'))}",
                "",
                "### Canonical JSON",
                "",
                "```json",
                json.dumps(finding, indent=2, ensure_ascii=False, sort_keys=True),
                "```",
                "",
            ]
        )
    return "\n".join(lines)


def rendered_files(root: Path) -> dict[str, str]:
    findings_data = load_json(root / "findings.json")
    coverage_data = load_json(root / "coverage.json")
    return {
        "09-implementation-sequence.md": render_implementation(findings_data),
        "10-review-coverage.md": render_coverage(coverage_data, findings_data),
        "11-findings-register.md": render_findings(findings_data),
    }


def render_to_disk(root: Path) -> None:
    for name, content in rendered_files(root).items():
        (root / name).write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("teardown", type=Path, help="Path to the seo-teardown directory")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check generated files without writing them",
    )
    args = parser.parse_args()
    root = args.teardown.resolve()
    expected = rendered_files(root)
    if args.check:
        mismatches = []
        for name, content in expected.items():
            path = root / name
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                mismatches.append(name)
        if mismatches:
            print("Generated handoff files are stale or missing:")
            for name in mismatches:
                print(f"- {name}")
            return 1
        print("Generated handoff files match canonical JSON")
        return 0
    for name, content in expected.items():
        (root / name).write_text(content, encoding="utf-8")
        print(f"Rendered {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
