from __future__ import annotations
import json,tempfile,unittest
from pathlib import Path
from validate_ux_ui_teardown import validate
import render_handoff

def write_fixture(root:Path,complete=True):
    evid=[
      {'id':'EVID-001','evidence_class':'rendered_observation','title':'rendered','locator':'prod','accessed_at':'2026-10-06','summary':'observed UI','limitations':[]},
      {'id':'EVID-002','evidence_class':'competitor_measurement','title':'measurement A','locator':'source-a','accessed_at':'2026-10-06','summary':'measured competitor A','limitations':[]},
      {'id':'EVID-003','evidence_class':'competitor_measurement','title':'measurement B','locator':'source-b','accessed_at':'2026-10-06','summary':'measured competitor B','limitations':[]},
      {'id':'EVID-004','evidence_class':'competitor_observation','title':'comparison','locator':'competitors','accessed_at':'2026-10-06','summary':'compared equivalent surfaces','limitations':[]},
    ]
    f={'schema_version':'ux-ui-teardown-v2','audit':{'project_name':'Fixture','project_locator':'repo','audited_revision':'abc','production_locator':'https://example.test','production_revision_status':'verified','audit_start_date':'2026-10-06','audit_end_date':'2026-10-06','review_status':'complete' if complete else 'provisional','project_type':'website','audience_scope':'global','primary_user_groups':['buyer'],'primary_goals':['complete task'],'owner_context':['high consideration'],'competitor_benchmark_required':True,'competitor_benchmark_reason':'public commercial product'},'evidence_sources':evid,
    'competitor_set':[{'id':'COMP-001','name':'A','locator':'a','selection_status':'measured','selection_evidence_ids':['EVID-002'],'comparison_evidence_ids':['EVID-004'],'relevance_reason':'measured leader','surfaces_compared':['home'],'limitations':[]},{'id':'COMP-002','name':'B','locator':'b','selection_status':'measured','selection_evidence_ids':['EVID-003'],'comparison_evidence_ids':['EVID-004'],'relevance_reason':'measured leader','surfaces_compared':['home'],'limitations':[]}],
    'journeys':[{'id':'JOURNEY-001','title':'primary','user_group':'buyer','trigger':'arrives','intended_outcome':'finish','criticality':'primary','steps':['start','finish'],'effort_budget':'contextual','engagement_intent':'help user choose','expected_payoff':'relevant result','context_notes':'guided flow appropriate','viewport_ids':['VIEW-001','VIEW-002'],'input_modes':['pointer_touch','keyboard'],'state_ids':['STATE-001'],'evidence_ids':['EVID-001'],'status':'passed','limitations':[]}],
    'experience_assessments':[{'id':'EXP-001','journey_ids':['JOURNEY-001'],'surface_target':'home','axis':'visual_craft','verdict':'strong','confidence':'high','evidence_ids':['EVID-001'],'competitor_ids':[],'observation':'coherent hierarchy','reasoning':'spacing and composition are consistent','desired_direction':'preserve'},{'id':'EXP-002','journey_ids':['JOURNEY-001'],'surface_target':'home','axis':'color_system','verdict':'strong','confidence':'high','evidence_ids':['EVID-001'],'competitor_ids':[],'observation':'coherent palette','reasoning':'surface and CTA colors have clear roles','desired_direction':'preserve'},{'id':'EXP-003','journey_ids':['JOURNEY-001'],'surface_target':'home','axis':'audience_fit','verdict':'appropriate','confidence':'medium','evidence_ids':['EVID-001'],'competitor_ids':[],'observation':'appropriate for audience','reasoning':'tone and scope fit target','desired_direction':'preserve'},{'id':'EXP-004','journey_ids':['JOURNEY-001'],'surface_target':'flow','axis':'engagement_quality','verdict':'productive','confidence':'high','evidence_ids':['EVID-001'],'competitor_ids':['COMP-001','COMP-002'],'observation':'effort produces relevance','reasoning':'choices narrow later information','desired_direction':'preserve'}],
    'findings':[{'id':'UXUI-001','title':'Retain guided relevance','kind':'strength','domains':['ux.engagement'],'status':'retained_strength','severity':'informational','confidence':'high','verification_state':'observed','judgment_basis':'observed_behavior','standard_refs':[],'journey_ids':['JOURNEY-001'],'surface_targets':['flow'],'evidence_ids':['EVID-001'],'competitor_ids':[],'observed_condition':'choices narrow later content','desired_condition':'preserve useful participation','user_consequence':'less irrelevant information','business_risk':'losing specificity would weaken experience','recommendation':'','acceptance_criteria':['guided choices continue to affect later content'],'verification_methods':['rerun flow'],'implementation_targets':[],'preservation_constraints':['do not flatten into generic form'],'dependencies':[],'conflicts':[],'non_goals':[]} ]}
    c={'schema_version':'ux-ui-teardown-coverage-v2','review_status':f['audit']['review_status'],'access':[{'category':x,'status':'available' if x in {'production_experience','competitor_measurement'} else 'not_applicable','material_to_complete':x in {'production_experience','competitor_measurement'},'evidence_ids':['EVID-001'] if x=='production_experience' else (['EVID-002','EVID-003'] if x=='competitor_measurement' else []),'limitations':[],'next_step':'none'} for x in ['source_repository','production_experience','competitor_measurement','user_sentiment','design_system','assistive_technology']],
    'passes':[{'id':'ui_craft','materiality':'defining','status':'passed','finding_ids':['UXUI-001'],'evidence_ids':['EVID-001'],'limitations':[]},{'id':'ux_experience','materiality':'defining','status':'passed','finding_ids':['UXUI-001'],'evidence_ids':['EVID-001'],'limitations':[]},{'id':'competitive_calibration','materiality':'high','status':'passed','finding_ids':[],'evidence_ids':['EVID-002','EVID-003','EVID-004'],'limitations':[]},{'id':'accessibility_readability','materiality':'supporting','status':'passed','finding_ids':[],'evidence_ids':['EVID-001'],'limitations':[]}],
    'viewports':[{'id':'VIEW-001','label':'mobile','width':390,'height':844,'class':'narrow_mobile','status':'observed','journey_ids':['JOURNEY-001'],'evidence_ids':['EVID-001'],'limitations':[]},{'id':'VIEW-002','label':'desktop','width':1440,'height':1000,'class':'desktop','status':'observed','journey_ids':['JOURNEY-001'],'evidence_ids':['EVID-001'],'limitations':[]}],
    'input_modes':[{'mode':'pointer_touch','status':'observed','journey_ids':['JOURNEY-001'],'evidence_ids':['EVID-001'],'limitations':[]},{'mode':'keyboard','status':'observed','journey_ids':['JOURNEY-001'],'evidence_ids':['EVID-001'],'limitations':[]},{'mode':'screen_reader','status':'not_applicable','journey_ids':[],'evidence_ids':[],'limitations':[]},{'mode':'other','status':'not_applicable','journey_ids':[],'evidence_ids':[],'limitations':[]}],
    'state_coverage':[{'id':'STATE-001','state':'default','label':'default','journey_id':'JOURNEY-001','step':'start','surface_target':'flow','trigger':'load','status':'observed','viewport_ids':['VIEW-001','VIEW-002'],'input_modes':['pointer_touch','keyboard'],'evidence_ids':['EVID-001'],'finding_ids':['UXUI-001'],'limitations':[]}],
    'material_limitations':[],'validator':{'name':'validate_ux_ui_teardown.py','status':'passed','validated_at':'2026-10-06'}}
    (root/'findings.json').write_text(json.dumps(f,indent=2)); (root/'coverage.json').write_text(json.dumps(c,indent=2))

class Tests(unittest.TestCase):
    def pair(self):
        t=tempfile.TemporaryDirectory(); root=Path(t.name); write_fixture(root); return t,root
    def test_valid_complete(self):
        t,r=self.pair(); self.addCleanup(t.cleanup); self.assertEqual(validate(r),[])
    def test_complete_requires_measured_competitors(self):
        t,r=self.pair(); self.addCleanup(t.cleanup); d=json.loads((r/'findings.json').read_text()); d['competitor_set'][0]['selection_status']='owner_supplied'; d['competitor_set'][1]['selection_status']='owner_supplied'; (r/'findings.json').write_text(json.dumps(d)); self.assertTrue(any('at least two measured' in e for e in validate(r)))
    def test_global_mobile_does_not_cover_primary_journey(self):
        t,r=self.pair(); self.addCleanup(t.cleanup); c=json.loads((r/'coverage.json').read_text()); c['viewports'][0]['journey_ids']=[]; (r/'coverage.json').write_text(json.dumps(c)); self.assertTrue(any('JOURNEY-001 missing viewports' in e for e in validate(r)))
    def test_material_access_blocks_complete(self):
        t,r=self.pair(); self.addCleanup(t.cleanup); c=json.loads((r/'coverage.json').read_text()); next(x for x in c['access'] if x['category']=='competitor_measurement')['status']='partial'; (r/'coverage.json').write_text(json.dumps(c)); self.assertTrue(any('material access' in e for e in validate(r)))
    def test_aesthetic_preference_cannot_be_high(self):
        t,r=self.pair(); self.addCleanup(t.cleanup); d=json.loads((r/'findings.json').read_text()); x=d['findings'][0]; x['kind']='gap'; x['status']='open'; x['severity']='high'; x['judgment_basis']='aesthetic_preference'; x['recommendation']='change'; (r/'findings.json').write_text(json.dumps(d)); self.assertTrue(any('aesthetic_preference' in e for e in validate(r)))
    def test_visual_craft_alone_not_critical(self):
        t,r=self.pair(); self.addCleanup(t.cleanup); d=json.loads((r/'findings.json').read_text()); x=d['findings'][0]; x['kind']='gap'; x['status']='open'; x['severity']='critical'; x['judgment_basis']='visual_craft'; x['recommendation']='fix'; (r/'findings.json').write_text(json.dumps(d)); self.assertTrue(any('visual_craft alone' in e for e in validate(r)))
    def test_malformed_lists_return_errors_not_traceback(self):
        t,r=self.pair(); self.addCleanup(t.cleanup); c=json.loads((r/'coverage.json').read_text()); c['viewports'][0]['journey_ids']=5; (r/'coverage.json').write_text(json.dumps(c)); errors=validate(r); self.assertTrue(errors)
    def test_screen_reader_not_required_for_complete(self):
        t,r=self.pair(); self.addCleanup(t.cleanup); self.assertEqual(validate(r),[])
    def test_renderer_deterministic(self):
        t,r=self.pair(); self.addCleanup(t.cleanup); self.assertEqual(render_handoff.render(r),render_handoff.render(r))
if __name__=='__main__': unittest.main()
