#!/usr/bin/env python3
"""Render deterministic Markdown registers from canonical seo-revision JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


NOTICE = "<!-- Generated by seo-revision/scripts/render_revision.py. Do not edit directly. -->"


def load_revision(root: Path) -> dict[str, Any]:
    value = json.loads((root / "revision.json").read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("revision.json must contain an object")
    return value


def text(value: Any) -> str:
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, (int, float)):
        return str(value)
    value = str(value).strip()
    return value or "None"


def inline(values: Any) -> str:
    if not isinstance(values, list) or not values:
        return "None"
    return ", ".join(text(item) for item in values)


def cell(value: Any) -> str:
    return text(value).replace("|", "\\|").replace("\n", "<br>")


def bullets(values: Any) -> list[str]:
    if not isinstance(values, list) or not values:
        return ["- None"]
    return [f"- {text(item)}" for item in values]


def header(title: str) -> list[str]:
    return [NOTICE, "", f"# {title}", ""]


def render_decisions(data: dict[str, Any]) -> str:
    teardown = data.get("teardown", {})
    lines = header("Decisions, authority, and scope")
    lines.extend(
        [
            f"**Mode:** {text(data.get('mode'))}",
            f"**Project:** {text(data.get('project', {}).get('name'))}",
            f"**Teardown path:** {text(teardown.get('path'))}",
            f"**Teardown findings schema:** {text(teardown.get('findings_schema'))}",
            f"**Teardown coverage schema:** {text(teardown.get('coverage_schema'))}",
            f"**Teardown review status:** {text(teardown.get('review_status'))}",
            f"**Upstream validator:** {text(teardown.get('validator_result'))}",
            "",
            "## Owner decision packet",
            "",
        ]
    )
    decisions = data.get("decisions", [])
    if not decisions:
        lines.append("None")
    for decision in decisions:
        lines.extend(
            [
                f"### {text(decision.get('id'))} — {text(decision.get('question'))}",
                "",
                f"- **Findings:** {inline(decision.get('finding_ids'))}",
                f"- **Status:** {text(decision.get('status'))}",
                f"- **Recommendation:** {text(decision.get('recommendation'))}",
                f"- **Owner selection:** {text(decision.get('owner_selection'))}",
                f"- **Safe default:** {text(decision.get('safe_default'))}",
                f"- **Consequences:** {inline(decision.get('consequences'))}",
                f"- **Prerequisites:** {inline(decision.get('prerequisites'))}",
                f"- **Reversibility:** {text(decision.get('reversibility'))}",
                "",
                "| Option | Label | Consequences | Prerequisites | Reversibility |",
                "|---|---|---|---|---|",
            ]
        )
        for option in decision.get("options", []):
            lines.append(
                f"| {cell(option.get('id'))} | {cell(option.get('label'))} | "
                f"{cell(inline(option.get('consequences')))} | "
                f"{cell(inline(option.get('prerequisites')))} | "
                f"{cell(option.get('reversibility'))} |"
            )
        lines.append("")

    lines.extend(
        [
            "## Authority matrix",
            "",
            "| Authority | State | Scope | Evidence | Limitations |",
            "|---|---|---|---|---|",
        ]
    )
    for item in data.get("authority_matrix", []):
        lines.append(
            f"| {cell(item.get('id'))} | {cell(item.get('state'))} | "
            f"{cell(item.get('scope'))} | {cell(inline(item.get('evidence_ids')))} | "
            f"{cell(inline(item.get('limitations')))} |"
        )
    lines.extend(["", "## Finding approval matrix", "", "| Finding | Approval | Revalidation | Disposition |", "|---|---|---|---|"])
    for finding in sorted(data.get("findings", []), key=lambda x: x.get("sequence", 0)):
        lines.append(
            f"| {cell(finding.get('id'))} | {cell(finding.get('approval'))} | "
            f"{cell(finding.get('revalidation'))} | {cell(finding.get('disposition'))} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_baseline(data: dict[str, Any]) -> str:
    workspace = data.get("workspace", {})
    trace = data.get("coverage_trace", {})
    lines = header("Baseline, drift, and revalidation")
    lines.extend(
        [
            f"**Implementation start:** {text(workspace.get('implementation_start_revision'))}",
            f"**Product endpoint:** {text(workspace.get('product_endpoint'))}",
            f"**Endpoint kind:** {text(workspace.get('endpoint_kind'))}",
            f"**Artifact relationship:** {text(workspace.get('artifact_relationship'))}",
            f"**Existing work reconciled:** {text(workspace.get('existing_work_reconciled'))}",
            "",
            "## Existing work inventory",
            "",
            f"- **Staged:** {inline(workspace.get('staged_paths'))}",
            f"- **Unstaged:** {inline(workspace.get('unstaged_paths'))}",
            f"- **Untracked:** {inline(workspace.get('untracked_paths'))}",
            f"- **Baseline evidence:** {inline(workspace.get('baseline_evidence_ids'))}",
            "",
            "## Finding revalidation",
            "",
            "| Sequence | Finding | Revalidation | Reason | Dependencies | Completion gates |",
            "|---:|---|---|---|---|---|",
        ]
    )
    for finding in sorted(data.get("findings", []), key=lambda x: x.get("sequence", 0)):
        lines.append(
            f"| {cell(finding.get('sequence'))} | {cell(finding.get('id'))} | "
            f"{cell(finding.get('revalidation'))} | {cell(finding.get('reason'))} | "
            f"{cell(inline(finding.get('dependencies')))} | {cell(inline(finding.get('completion_gates')))} |"
        )

    lines.extend(["", "## Access trace", "", "| Category | Source status | Disposition | Completion gate | Evidence |", "|---|---|---|---|---|"])
    for item in trace.get("access", []):
        lines.append(
            f"| {cell(item.get('category'))} | {cell(item.get('source_status'))} | "
            f"{cell(item.get('disposition'))} | {cell(item.get('completion_gate'))} | "
            f"{cell(inline(item.get('evidence_ids')))} |"
        )

    lines.extend(["", "## Material limitations", "", "| Limitation | Source status | Disposition | Completion gate | Evidence |", "|---|---|---|---|---|"])
    for item in trace.get("material_limitations", []):
        lines.append(
            f"| {cell(item.get('id'))} | {cell(item.get('source_status'))} | "
            f"{cell(item.get('disposition'))} | {cell(item.get('completion_gate'))} | "
            f"{cell(inline(item.get('evidence_ids')))} |"
        )
    if not trace.get("material_limitations"):
        lines.append("| None | None | None | None | None |")

    lines.extend(["", "## Deliberate non-pursuits", ""])
    for item in trace.get("deliberate_non_pursuits", []):
        lines.append(
            f"- **{text(item.get('topic'))}:** {text(item.get('rationale'))} "
            f"Preservation rule: {text(item.get('preservation_rule'))}"
        )
    if not trace.get("deliberate_non_pursuits"):
        lines.append("- None")
    lines.append("")
    return "\n".join(lines)


def render_plan(data: dict[str, Any]) -> str:
    lines = header("Execution, rollout, and measurement plan")
    lines.extend(["## Dependency-aware sequence", "", "| Sequence | Finding | Approval | Disposition | Changes | Experiments |", "|---:|---|---|---|---|---|"])
    for finding in sorted(data.get("findings", []), key=lambda x: x.get("sequence", 0)):
        lines.append(
            f"| {cell(finding.get('sequence'))} | {cell(finding.get('id'))} | "
            f"{cell(finding.get('approval'))} | {cell(finding.get('disposition'))} | "
            f"{cell(inline(finding.get('change_ids')))} | {cell(inline(finding.get('experiment_ids')))} |"
        )

    lines.extend(["", "## Surface-check completion gates", "", "| Check | Source status | Disposition | Completion gate | Evidence |", "|---|---|---|---|---|"])
    for item in data.get("coverage_trace", {}).get("surface_checks", []):
        lines.append(
            f"| {cell(item.get('id'))} | {cell(item.get('source_status'))} | "
            f"{cell(item.get('disposition'))} | {cell(item.get('completion_gate'))} | "
            f"{cell(inline(item.get('evidence_ids')))} |"
        )

    lines.extend(["", "## Rollouts", ""])
    for rollout in data.get("rollouts", []):
        lines.extend(
            [
                f"### {text(rollout.get('id'))}",
                "",
                f"- **Changes:** {inline(rollout.get('change_ids'))}",
                f"- **State:** {text(rollout.get('state'))}",
                f"- **Inventory:** {inline(rollout.get('inventory'))}",
                f"- **Representative samples:** {inline(rollout.get('representative_samples'))}",
                f"- **Collision checks:** {inline(rollout.get('collision_checks'))}",
                f"- **Rollback:** {text(rollout.get('rollback_plan'))}",
                f"- **Evidence:** {inline(rollout.get('evidence_ids'))}",
                "",
            ]
        )
    if not data.get("rollouts"):
        lines.append("None")

    lines.extend(["", "## Experiments", ""])
    for experiment in data.get("experiments", []):
        lines.extend(
            [
                f"### {text(experiment.get('id'))} — {text(experiment.get('hypothesis'))}",
                "",
                f"- **Status:** {text(experiment.get('status'))}",
                f"- **Findings:** {inline(experiment.get('finding_ids'))}",
                f"- **Segment:** {text(experiment.get('segment'))}",
                f"- **Pages/queries:** {inline(experiment.get('affected_pages_queries'))}",
                f"- **Baseline:** {text(experiment.get('baseline'))}",
                f"- **Primary metric:** {text(experiment.get('primary_metric'))}",
                f"- **Guardrails:** {inline(experiment.get('guardrails'))}",
                f"- **Sample requirement:** {text(experiment.get('sample_requirement'))}",
                f"- **Time to evidence:** {text(experiment.get('expected_time_to_evidence'))}",
                f"- **Decision rule:** {text(experiment.get('decision_rule'))}",
                f"- **Owner / next review:** {text(experiment.get('observation_owner'))} / {text(experiment.get('next_review_at'))}",
                "",
            ]
        )
    if not data.get("experiments"):
        lines.append("None")
    lines.append("")
    return "\n".join(lines)


def render_implementation(data: dict[str, Any]) -> str:
    change_map = {item.get("id"): item for item in data.get("changes", [])}
    title = (
        "Implementation ledger"
        if data.get("mode") == "implementation"
        else "Implementation ledger (planning-only — no implementation performed)"
    )
    lines = header(title)
    lines.append(
        "Every teardown finding appears exactly once below. "
        + (
            "The records describe completed or blocked execution."
            if data.get("mode") == "implementation"
            else "All executable work remains a plan or explicit blocker; no product change is claimed."
        )
    )
    lines.append("")
    for finding in sorted(data.get("findings", []), key=lambda x: x.get("sequence", 0)):
        lines.extend(
            [
                f"## {text(finding.get('id'))} — {text(finding.get('title'))}",
                "",
                f"- **Approval:** {text(finding.get('approval'))}",
                f"- **Revalidation:** {text(finding.get('revalidation'))}",
                f"- **Disposition:** {text(finding.get('disposition'))}",
                f"- **Sequence:** {text(finding.get('sequence'))}",
                f"- **Dependencies:** {inline(finding.get('dependencies'))}",
                f"- **Reason:** {text(finding.get('reason'))}",
                f"- **Evidence:** {inline(finding.get('evidence_ids'))}",
                f"- **Changes:** {inline(finding.get('change_ids'))}",
                f"- **Experiments:** {inline(finding.get('experiment_ids'))}",
                f"- **Completion gates:** {inline(finding.get('completion_gates'))}",
                f"- **Notes:** {inline(finding.get('notes'))}",
                "",
                "### Acceptance results",
                "",
                "| Criterion | Status | Evidence | Observation |",
                "|---|---|---|---|",
            ]
        )
        for result in finding.get("acceptance_results", []):
            lines.append(
                f"| {cell(result.get('criterion'))} | {cell(result.get('status'))} | "
                f"{cell(inline(result.get('evidence_ids')))} | {cell(result.get('observation'))} |"
            )
        lines.extend(["", "### Mapped changes", ""])
        for change_id in finding.get("change_ids", []):
            change = change_map.get(change_id, {})
            lines.append(
                f"- **{change_id}:** {text(change.get('description'))}; "
                f"targets={inline(change.get('targets'))}; risk={text(change.get('risk_level'))}"
            )
        if not finding.get("change_ids"):
            lines.append("- None")
        lines.append("")

    lines.extend(["# Change inventory", ""])
    for change in data.get("changes", []):
        lines.extend(
            [
                f"### {text(change.get('id'))} — {text(change.get('description'))}",
                "",
                f"- **Scope:** {text(change.get('scope'))}",
                f"- **Findings:** {inline(change.get('finding_ids'))}",
                f"- **Convergence:** {inline(change.get('convergence_ids'))}",
                f"- **Targets:** {inline(change.get('targets'))}",
                f"- **External authorities:** {inline(change.get('external_authority_ids'))}",
                f"- **Risk:** {text(change.get('risk_level'))} — {inline(change.get('risk_categories'))}",
                f"- **Rollout:** {text(change.get('rollout_id'))}",
                f"- **Evidence:** {inline(change.get('evidence_ids'))}",
                "",
            ]
        )
    if not data.get("changes"):
        lines.append("None — no implementation changes recorded.")
    lines.append("")
    return "\n".join(lines)


def render_convergence(data: dict[str, Any]) -> str:
    lines = header("Convergence ledger")
    lines.append("Actionable review leads are recorded below after current-state revalidation.")
    lines.append("")
    for finding in data.get("convergence_findings", []):
        lines.extend(
            [
                f"## {text(finding.get('id'))} — {text(finding.get('title'))}",
                "",
                f"- **Source:** {text(finding.get('source'))}",
                f"- **Severity:** {text(finding.get('severity'))}",
                f"- **Status:** {text(finding.get('status'))}",
                f"- **Reason:** {text(finding.get('reason'))}",
                f"- **Reopened findings:** {inline(finding.get('reopened_finding_ids'))}",
                f"- **Changes:** {inline(finding.get('change_ids'))}",
                f"- **Evidence:** {inline(finding.get('evidence_ids'))}",
                "",
            ]
        )
    if not data.get("convergence_findings"):
        lines.append("None")
    lines.append("")
    return "\n".join(lines)


def render_verification(data: dict[str, Any]) -> str:
    lines = header("Production, search, and experiment verification")
    lines.extend(["## Evidence ledger", "", "| Evidence | Level | Method | Status | Observed | Observation | Limitations |", "|---|---|---|---|---|---|---|"])
    for item in data.get("evidence", []):
        lines.append(
            f"| {cell(item.get('id'))} | {cell(item.get('level'))} | "
            f"{cell(item.get('method'))} | {cell(item.get('status'))} | "
            f"{cell(item.get('observed_at'))} | {cell(item.get('observation'))} | "
            f"{cell(inline(item.get('limitations')))} |"
        )

    lines.extend(["", "## URL verification", ""])
    for item in data.get("url_verifications", []):
        lines.extend(
            [
                f"### {text(item.get('id'))} — {text(item.get('url'))}",
                "",
                f"- **Environment:** {text(item.get('environment'))}",
                f"- **Evidence:** {inline(item.get('evidence_ids'))}",
                f"- **Limitations:** {inline(item.get('limitations'))}",
                "",
                "| Method | Status | Observation | Evidence | Limitations |",
                "|---|---|---|---|---|",
            ]
        )
        for method in item.get("method_evidence", []):
            lines.append(
                f"| {cell(method.get('method'))} | {cell(method.get('status'))} | "
                f"{cell(method.get('observation'))} | {cell(inline(method.get('evidence_ids')))} | "
                f"{cell(inline(method.get('limitations')))} |"
            )
        lines.extend(["", "| Dimension | Status | Value | Methods | Evidence | Limitations |", "|---|---|---|---|---|---|"])
        for observation in item.get("observations", []):
            lines.append(
                f"| {cell(observation.get('dimension'))} | {cell(observation.get('status'))} | "
                f"{cell(observation.get('value'))} | {cell(inline(observation.get('supported_by_methods')))} | "
                f"{cell(inline(observation.get('evidence_ids')))} | "
                f"{cell(inline(observation.get('limitations')))} |"
            )
        lines.append("")
    if not data.get("url_verifications"):
        lines.append("None")

    lines.extend(["", "## Experiment state", ""])
    for experiment in data.get("experiments", []):
        lines.append(
            f"- **{text(experiment.get('id'))}:** {text(experiment.get('status'))}; "
            f"metric={text(experiment.get('primary_metric'))}; next review={text(experiment.get('next_review_at'))}; "
            f"evidence={inline(experiment.get('evidence_ids'))}"
        )
    if not data.get("experiments"):
        lines.append("- None")
    lines.append("")
    return "\n".join(lines)


def render_readiness(data: dict[str, Any]) -> str:
    readiness = data.get("readiness", {})
    workspace = data.get("workspace", {})
    delivery = readiness.get("delivery", {})
    lines = header("Readiness and handoff")
    lines.extend(
        [
            f"**Revision status:** {text(readiness.get('revision_status'))}",
            f"**Product endpoint:** {text(workspace.get('product_endpoint'))}",
            f"**Artifact relationship:** {text(workspace.get('artifact_relationship'))}",
            f"**Review convergence:** {text(readiness.get('review_convergence'))}",
            f"**Integration readiness:** {text(readiness.get('integration'))}",
            f"**Deployment readiness:** {text(readiness.get('deployment'))}",
            f"**Publication readiness:** {text(readiness.get('publication'))}",
            f"**Search validation:** {text(readiness.get('search_validation'))}",
            f"**Experiment status:** {text(readiness.get('experiment_status'))}",
            f"**Authorization summary:** {text(readiness.get('authorization_summary'))}",
            f"**Convergence evidence:** {inline(readiness.get('convergence_evidence_ids'))}",
            "",
            "## Delivery facts",
            "",
            "| Delivery action | State |",
            "|---|---|",
        ]
    )
    for key in (
        "committed",
        "pushed",
        "pull_request",
        "merged",
        "deployed",
        "published",
        "search_platform_actions",
        "external_profile_actions",
    ):
        item = delivery.get(key, {})
        lines.append(
            f"| {key.replace('_', ' ').title()} | {cell(item.get('state'))}; "
            f"evidence={cell(inline(item.get('evidence_ids')))}; "
            f"{cell(item.get('observation'))} |"
        )
    lines.extend(["", "## Unverified outcomes", ""])
    lines.extend(bullets(readiness.get("unverified_outcomes")))
    lines.extend(["", "## Follow-up actions", ""])
    lines.extend(bullets(readiness.get("follow_up_actions")))
    lines.extend(
        [
            "",
            "## Counts",
            "",
            f"- Teardown findings: {len(data.get('findings', []))}",
            f"- Recorded changes: {len(data.get('changes', []))}",
            f"- Convergence findings: {len(data.get('convergence_findings', []))}",
            f"- Evidence records: {len(data.get('evidence', []))}",
            f"- URL verifications: {len(data.get('url_verifications', []))}",
            f"- Experiments: {len(data.get('experiments', []))}",
            "",
        ]
    )
    return "\n".join(lines)


def rendered_files(root: Path) -> dict[str, str]:
    data = load_revision(root)
    return {
        "00-decisions-authority-and-scope.md": render_decisions(data),
        "01-baseline-drift-and-revalidation.md": render_baseline(data),
        "02-execution-rollout-and-measurement-plan.md": render_plan(data),
        "03-implementation-ledger.md": render_implementation(data),
        "04-convergence-ledger.md": render_convergence(data),
        "05-production-search-and-experiment-verification.md": render_verification(data),
        "06-readiness-and-handoff.md": render_readiness(data),
    }


def render_to_disk(root: Path) -> None:
    for name, content in rendered_files(root).items():
        (root / name).write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("revision", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.revision.resolve()
    expected = rendered_files(root)
    if args.check:
        mismatches = [
            name
            for name, content in expected.items()
            if not (root / name).is_file()
            or (root / name).read_text(encoding="utf-8") != content
        ]
        if mismatches:
            print("Generated revision files are stale or missing:")
            for name in mismatches:
                print(f"- {name}")
            return 1
        print("Generated revision files match canonical JSON")
        return 0
    for name, content in expected.items():
        (root / name).write_text(content, encoding="utf-8")
        print(f"Rendered {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
