#!/usr/bin/env python3
"""Render deterministic Markdown registers from canonical brand teardown JSON."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any


NOTICE = "<!-- Generated by brand-teardown/scripts/render_handoff.py. Do not edit directly. -->"


def load_object(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def text(value: Any) -> str:
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, (int, float)):
        return str(value)
    rendered = str(value).strip()
    return rendered or "None"


def inline(values: Any) -> str:
    if not isinstance(values, list) or not values:
        return "None"
    return ", ".join(text(item) for item in values)


def bullets(values: Any) -> list[str]:
    if not isinstance(values, list) or not values:
        return ["- None"]
    return [f"- {text(item)}" for item in values]


def cell(value: Any) -> str:
    return text(value).replace("|", "\\|").replace("\n", "<br>")


def header(title: str) -> list[str]:
    return [NOTICE, "", f"# {title}", ""]


def render_findings(data: dict[str, Any]) -> str:
    evidence = {item.get("id"): item for item in data.get("evidence_sources", []) if isinstance(item, dict)}
    findings = sorted(data.get("findings", []), key=lambda item: item.get("id", ""))
    lines = header("Brand findings register")
    lines.extend(["`findings.json` is authoritative.", ""])
    for finding in findings:
        priority = finding.get("priority", {})
        implementation = finding.get("implementation", {})
        lines.extend(
            [
                f"## {text(finding.get('id'))} — {text(finding.get('title'))}",
                "",
                f"- **Kind:** {text(finding.get('kind'))}",
                f"- **Module:** {text(finding.get('module'))}",
                f"- **Status:** {text(finding.get('status'))}",
                f"- **Severity:** {text(finding.get('severity'))}",
                f"- **Confidence:** {text(finding.get('confidence'))}",
                f"- **Evidence quality:** {text(finding.get('evidence_quality'))}",
                f"- **Claim state:** {text(finding.get('claim_state'))}",
                f"- **Judgment basis:** {text(finding.get('judgment_basis'))}",
                f"- **Outcome evidence:** {text(finding.get('outcome_evidence_status'))}",
                f"- **Affected brands:** {inline(finding.get('affected_brands'))}",
                f"- **Affected audiences:** {inline(finding.get('affected_audiences'))}",
                f"- **Affected surfaces:** {inline(finding.get('affected_surfaces'))}",
                f"- **Affected channels:** {inline(finding.get('affected_channels'))}",
                f"- **Dependencies:** {inline(finding.get('dependencies'))}",
                f"- **Conflicts:** {inline(finding.get('conflicts'))}",
                f"- **Blocker:** {text(finding.get('blocker'))}",
                f"- **Owner decision:** {text(finding.get('owner_decision'))}",
                f"- **Responsible discipline:** {text(finding.get('responsible_discipline'))}",
                "",
                "### Evidence",
                "",
            ]
        )
        links = {
            item.get("evidence_id"): item
            for item in finding.get("evidence_links", [])
            if isinstance(item, dict) and isinstance(item.get("evidence_id"), str)
        }
        for evidence_id in finding.get("evidence_ids", []):
            source = evidence.get(evidence_id, {})
            link = links.get(evidence_id, {})
            lines.append(
                f"- **{evidence_id} — {text(source.get('title'))}:** role={text(link.get('role'))}; "
                f"claim={text(link.get('claim'))}; class={text(source.get('evidence_class'))}; "
                f"scope={text(source.get('evidence_scope'))}; accessed={text(source.get('accessed_at'))}; "
                f"limitations={text(source.get('limitations'))}"
            )
        lines.extend(
            [
                "",
                "### Observed and desired condition",
                "",
                f"**Observed:** {text(finding.get('observed_condition'))}",
                "",
                f"**Desired:** {text(finding.get('desired_condition'))}",
                "",
                "### Consequences",
                "",
                f"- **Brand:** {text(finding.get('brand_consequence'))}",
                f"- **Business or conversion:** {text(finding.get('business_consequence'))}",
                f"- **Trust:** {text(finding.get('trust_consequence'))}",
                f"- **Differentiation:** {text(finding.get('differentiation_consequence'))}",
                f"- **Recall or recognition:** {text(finding.get('recognition_consequence'))}",
                f"- **Proof or claim gap:** {text(finding.get('proof_or_claim_gap'))}",
                "",
                "### Recommended direction",
                "",
                text(finding.get("recommendation")),
                "",
                "### Acceptance criteria",
                "",
            ]
        )
        lines.extend(bullets(finding.get("acceptance_criteria")))
        lines.extend(["", "### Verification methods", ""])
        lines.extend(bullets(finding.get("verification_methods")))
        lines.extend(["", "### Preservation constraints", ""])
        lines.extend(bullets(finding.get("preservation_constraints")))
        lines.extend(
            [
                "",
                "### Priority and implementation handoff",
                "",
                f"- **Brand impact:** {text(priority.get('brand_impact'))}",
                f"- **Business impact:** {text(priority.get('business_impact'))}",
                f"- **Effort:** {text(priority.get('effort'))}",
                f"- **Reversibility:** {text(priority.get('reversibility'))}",
                f"- **Phase:** {text(implementation.get('phase_id'))}",
                f"- **Order:** {text(implementation.get('order'))}",
                f"- **Disposition:** {text(implementation.get('disposition'))}",
                f"- **Rationale:** {text(implementation.get('rationale'))}",
                f"- **Validation gate:** {text(implementation.get('validation_gate'))}",
                f"- **Targets:** {inline(implementation.get('targets'))}",
                f"- **Non-goals:** {inline(implementation.get('non_goals'))}",
                f"- **Owner or external actions:** {inline(implementation.get('owner_or_external_actions'))}",
                "",
                "### Implementation notes",
                "",
            ]
        )
        lines.extend(bullets(finding.get("implementation_notes")))
        lines.extend(["", "### Canonical JSON", "", "```json", json.dumps(finding, indent=2, ensure_ascii=False, sort_keys=True), "```", ""])
    return "\n".join(lines)


def render_decisions(data: dict[str, Any]) -> str:
    findings = [
        item for item in data.get("findings", [])
        if isinstance(item, dict) and item.get("status") in {"decision_required", "blocked"}
    ]
    lines = header("Owner decisions and blockers")
    if not findings:
        lines.extend(["None", ""])
        return "\n".join(lines)
    for finding in sorted(findings, key=lambda item: item.get("implementation", {}).get("order", 0)):
        lines.extend(
            [
                f"## {text(finding.get('id'))} — {text(finding.get('title'))}",
                "",
                f"- **Status:** {text(finding.get('status'))}",
                f"- **Owner decision:** {text(finding.get('owner_decision'))}",
                f"- **Blocker:** {text(finding.get('blocker'))}",
                f"- **Recommended direction:** {text(finding.get('recommendation'))}",
                f"- **Dependencies:** {inline(finding.get('dependencies'))}",
                f"- **Affected brands:** {inline(finding.get('affected_brands'))}",
                f"- **Affected audiences:** {inline(finding.get('affected_audiences'))}",
                f"- **Required owner/external actions:** {inline(finding.get('implementation', {}).get('owner_or_external_actions'))}",
                f"- **Consequence if unresolved:** {text(finding.get('business_consequence'))}",
                "",
            ]
        )
    return "\n".join(lines)


def render_sequence(data: dict[str, Any]) -> str:
    finding_map = {item.get("id"): item for item in data.get("findings", []) if isinstance(item, dict)}
    audit = data.get("audit", {})
    lines = header("Dependency-aware implementation sequence")
    lines.extend(
        [
            f"**Review status:** {text(audit.get('review_status'))}",
            "",
            "This sequence is a recommendation, not owner approval. Outcome verification remains separate from implementation verification.",
            "",
        ]
    )
    for phase in data.get("implementation_phases", []):
        lines.extend(
            [
                f"## {text(phase.get('id'))} — {text(phase.get('title'))}",
                "",
                f"- **Type:** {text(phase.get('phase_type'))}",
                f"- **Rationale:** {text(phase.get('rationale'))}",
                f"- **Validation gate:** {text(phase.get('validation_gate'))}",
                f"- **Expected outcome:** {text(phase.get('expected_outcome'))}",
                "",
                "| Finding | Order | Disposition | Severity | Status | Dependencies | Validation gate |",
                "|---|---:|---|---|---|---|---|",
            ]
        )
        phase_findings = [finding_map[fid] for fid in phase.get("finding_ids", []) if fid in finding_map]
        phase_findings.sort(key=lambda item: item.get("implementation", {}).get("order", 0))
        for finding in phase_findings:
            implementation = finding.get("implementation", {})
            lines.append(
                f"| {cell(finding.get('id'))} | {cell(implementation.get('order'))} | "
                f"{cell(implementation.get('disposition'))} | {cell(finding.get('severity'))} | "
                f"{cell(finding.get('status'))} | {cell(inline(finding.get('dependencies')))} | "
                f"{cell(implementation.get('validation_gate'))} |"
            )
        lines.append("")
    lines.extend(["## Complete finding ledger", ""])
    ordered = sorted(finding_map.values(), key=lambda item: item.get("implementation", {}).get("order", 0))
    for finding in ordered:
        impl = finding.get("implementation", {})
        lines.append(f"- {finding.get('id')} — phase {impl.get('phase_id')}, order {impl.get('order')}, disposition {impl.get('disposition')}")
    lines.append("")
    return "\n".join(lines)


def render_coverage(coverage: dict[str, Any], findings: dict[str, Any]) -> str:
    finding_items = findings.get("findings", [])
    evidence_items = findings.get("evidence_sources", [])
    severity = Counter(item.get("severity") for item in finding_items if isinstance(item, dict))
    status = Counter(item.get("status") for item in finding_items if isinstance(item, dict))
    kind = Counter(item.get("kind") for item in finding_items if isinstance(item, dict))
    lines = header("Review coverage and limitations")
    lines.extend([f"**Review status:** {text(coverage.get('review_status'))}", "", "## Access ledger", "", "| Category | Status | Material | Window | Evidence | Limitations | Next step |", "|---|---|---|---|---|---|---|"])
    for item in coverage.get("access", []):
        lines.append(
            f"| {cell(item.get('category'))} | {cell(item.get('status'))} | "
            f"{cell(item.get('material_to_comprehensive'))} | {cell(item.get('coverage_window'))} | "
            f"{cell(inline(item.get('evidence_ids')))} | {cell(inline(item.get('limitations')))} | {cell(item.get('next_step'))} |"
        )
    lines.extend(["", "## Module ledger", "", "| Module | Applicable | Materiality | Status | Checks | Findings | Evidence | Limitations | Next step |", "|---|---|---|---|---|---|---|---|---|"])
    for item in coverage.get("modules", []):
        lines.append(
            f"| {cell(item.get('id'))} | {cell(item.get('applicable'))} | {cell(item.get('materiality'))} | "
            f"{cell(item.get('status'))} | {cell(inline(item.get('check_ids')))} | "
            f"{cell(inline(item.get('finding_ids')))} | {cell(inline(item.get('evidence_ids')))} | "
            f"{cell(inline(item.get('limitations')))} | {cell(item.get('next_step'))} |"
        )
    lines.extend(["", "## Facet checks", "", "| Check | Module | Facet | Method | Status | Findings | Evidence | Method evidence | Work complete | Result | Unknowns | Limitation refs | Limitations |", "|---|---|---|---|---|---|---|---|---|---|---|---|---|"])
    for item in coverage.get("surface_checks", []):
        method_evidence = [
            f"{entry.get('evidence_id')} ({entry.get('role')}): {entry.get('observation')}"
            for entry in item.get("method_evidence", []) if isinstance(entry, dict)
        ]
        lines.append(
            f"| {cell(item.get('id'))} | {cell(item.get('module_id'))} | {cell(item.get('facet'))} | "
            f"{cell(item.get('method'))} | {cell(item.get('status'))} | {cell(inline(item.get('finding_ids')))} | "
            f"{cell(inline(item.get('evidence_ids')))} | {cell(inline(method_evidence))} | {cell(item.get('available_work_completed'))} | "
            f"{cell(item.get('result'))} | {cell(inline(item.get('unknowns')))} | "
            f"{cell(inline(item.get('limitation_refs')))} | {cell(inline(item.get('limitations')))} |"
        )
    lines.extend(["", "## Surface samples", "", "| Sample | Surface | Brand | Audience | Channel | Format | Method | Status | Observed | Findings | Evidence | Observations | Limitations |", "|---|---|---|---|---|---|---|---|---|---|---|---|---|"])
    for item in coverage.get("surface_samples", []):
        lines.append(
            f"| {cell(item.get('id'))} | {cell(item.get('surface'))} | {cell(item.get('brand'))} | "
            f"{cell(item.get('audience'))} | {cell(item.get('channel'))} | {cell(item.get('viewport_or_format'))} | "
            f"{cell(item.get('method'))} | {cell(item.get('status'))} | {cell(item.get('observed_at'))} | "
            f"{cell(inline(item.get('finding_ids')))} | {cell(inline(item.get('evidence_ids')))} | "
            f"{cell(inline(item.get('observations')))} | {cell(inline(item.get('limitations')))} |"
        )
    lines.extend(["", "## Competitor samples", "", "| Sample | Name | Relationship | Observed | Status | Category language | Trust | Offers | Visual patterns | Strengths | Strategic consequence | Evidence | Limitations |", "|---|---|---|---|---|---|---|---|---|---|---|---|---|"])
    for item in coverage.get("competitor_samples", []):
        lines.append(
            f"| {cell(item.get('id'))} | {cell(item.get('name'))} | {cell(item.get('relationship'))} | "
            f"{cell(item.get('observed_at'))} | {cell(item.get('status'))} | {cell(inline(item.get('category_language')))} | "
            f"{cell(inline(item.get('trust_conventions')))} | {cell(inline(item.get('offer_conventions')))} | "
            f"{cell(inline(item.get('visual_patterns')))} | {cell(inline(item.get('strengths')))} | "
            f"{cell(item.get('strategic_consequence'))} | {cell(inline(item.get('evidence_ids')))} | {cell(inline(item.get('limitations')))} |"
        )
    lines.extend(["", "## Material limitations", ""])
    if coverage.get("material_limitations"):
        for item in coverage.get("material_limitations", []):
            lines.append(
                f"- **{text(item.get('id'))}:** {text(item.get('description'))} "
                f"(status: {text(item.get('status'))}; modules: {inline(item.get('affected_module_ids'))}; "
                f"completion: {text(item.get('completion_requirement'))})"
            )
    else:
        lines.append("- None")
    lines.extend(["", "## Narrative reconciliation", "", "| Location | Finding IDs | Non-actionable explanation |", "|---|---|---|"])
    for item in coverage.get("narrative_reconciliation", []):
        lines.append(f"| {cell(item.get('location'))} | {cell(inline(item.get('finding_ids')))} | {cell(item.get('non_actionable_explanation'))} |")
    lines.extend(
        [
            "",
            "## Counts",
            "",
            f"- Evidence sources: {len(evidence_items)}",
            f"- Findings: {len(finding_items)}",
            f"- Claims: {len(findings.get('claims', []))}",
            f"- Severity: {', '.join(f'{key}={value}' for key, value in sorted(severity.items())) or 'None'}",
            f"- Status: {', '.join(f'{key}={value}' for key, value in sorted(status.items())) or 'None'}",
            f"- Kind: {', '.join(f'{key}={value}' for key, value in sorted(kind.items())) or 'None'}",
            "",
            "## Established-standard comparison",
            "",
            f"- **Standard:** {text(findings.get('audit', {}).get('established_standard'))}",
            f"- **Remaining gaps:** {inline(findings.get('audit', {}).get('remaining_standard_gaps'))}",
            "",
            "## Validator",
            "",
            f"- **Command:** `{text(coverage.get('validator', {}).get('command'))}`",
            f"- **Recorded result:** {text(coverage.get('validator', {}).get('result'))}",
            "",
        ]
    )
    return "\n".join(lines)


def render_claims(data: dict[str, Any]) -> str:
    evidence = {item.get("id"): item for item in data.get("evidence_sources", []) if isinstance(item, dict)}
    lines = header("Brand claim inventory")
    lines.extend(["`findings.json` is authoritative.", "", "| Claim | Brand | Type | State | Risk | Surfaces | Audiences | Evidence | Owner | Required action | Verification |", "|---|---|---|---|---|---|---|---|---|---|---|"])
    for claim in sorted(data.get("claims", []), key=lambda item: item.get("id", "")):
        evidence_text = []
        for evid in claim.get("evidence_ids", []):
            evidence_text.append(f"{evid}: {text(evidence.get(evid, {}).get('title'))}")
        claim_label = f"{claim.get('id')} — {claim.get('claim')}"
        lines.append(
            f"| {cell(claim_label)} | {cell(claim.get('brand'))} | "
            f"{cell(claim.get('claim_type'))} | {cell(claim.get('state'))} | {cell(claim.get('risk_level'))} | "
            f"{cell(inline(claim.get('surfaces')))} | {cell(inline(claim.get('audiences')))} | "
            f"{cell(inline(evidence_text))} | {cell(claim.get('owner'))} | {cell(claim.get('required_action'))} | "
            f"{cell(claim.get('verification_method'))} |"
        )
    lines.append("")
    return "\n".join(lines)


def rendered_files(root: Path) -> dict[str, str]:
    findings = load_object(root / "findings.json")
    coverage = load_object(root / "coverage.json")
    return {
        "09-findings-register.md": render_findings(findings),
        "10-owner-decisions.md": render_decisions(findings),
        "11-implementation-sequence.md": render_sequence(findings),
        "12-review-coverage-and-limitations.md": render_coverage(coverage, findings),
        "13-brand-claim-inventory.md": render_claims(findings),
    }


def render_to_disk(root: Path) -> None:
    for name, content in rendered_files(root).items():
        (root / name).write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("teardown", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.teardown.resolve()
    expected = rendered_files(root)
    if args.check:
        mismatches = [
            name for name, content in expected.items()
            if not (root / name).is_file() or (root / name).read_text(encoding="utf-8") != content
        ]
        if mismatches:
            print("Generated brand teardown files are stale or missing:")
            for name in mismatches:
                print(f"- {name}")
            return 1
        print("Generated brand teardown files match canonical JSON")
        return 0
    for name, content in expected.items():
        (root / name).write_text(content, encoding="utf-8")
        print(f"Rendered {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
